### ISSUE TITLE
LionWebModelConverter issues

### ISSUE THREAD

**Issue by alessiostalla** [Strumenta/kolasu#317]
- It's stateful and uses maps so it can't be reliably shared across threads;
- However, it doesn't allow to provide its `languageConverter` from the outside so if you don't share the model converter you have to re-export the used languages.

Either the maps should be made thread-safe, or it should be possible to pass the language converter as a constructor parameter.

**Comment by ftomassetti** [comment]
> It's stateful and uses maps so it can't be reliably shared across threads;

Yes, that is the case because otherwise references would cause the creation of different copies of the nodes (either in the LionWeb->Kolasu or the Kolasu->LionWeb scenario)

> However, it doesn't allow to provide its languageConverter from the outside so if you don't share the model converter you have to re-export the used languages.

Right, perhaps we can change that

> Either the maps should be made thread-safe, or it should be possible to pass the language converter as a constructor parameter.

The latter seems quite easy. Regarding maps thread-safe I guess it would make sense to do so. I do not have much experience with that but I can study the problem
