### ISSUE TITLE
Revise support for CLI utilities

### ISSUE THREAD

**Issue by ftomassetti** [Strumenta/kolasu#78]
Expand it to include code from RPGParser

**Comment by ftomassetti** [comment]
See:
https://github.com/Strumenta/kolasu/blob/master/core/src/main/kotlin/com/strumenta/kolasu/cli/CLI.kt
https://github.com/Strumenta/kolasu/blob/master/emf/src/main/kotlin/com/strumenta/kolasu/emf/cli/ParserCLIEMF.kt

**Comment by ftomassetti** [comment]
In core we may want to:
* Generate ASTs on file (as XML or JSON)
* Produce statistics on the number of errors
* Produce statistics on the types of nodes

We may want to specify the character encoding and verbosity

**Comment by ftomassetti** [comment]
I am reflecting on which command-line utilities we need.

I find it useful to have command-line tools to:
- Export the AST (XML, JSON, Debug format) on file or the command line
- Export the metamodel in EMF format (XMI, JSON)
- Export ASTs in EMF format (XMI, JSON)
- Print stats on the presence of nodes in a set of source files. @mctaverna and @loradd worked on similar tools for some analysis we did. What are your thoughts on this?
- Print stats on the errors that occurred while parsing files

@alessiostalla wrote two command line tools (one in core and one in EMF) which performed most of these things. Any suggestion for this?
I have been doing some experiments in [branch issue78](https://github.com/Strumenta/kolasu/tree/issue78).
So far, I have focused only on core, and I wanted to create two separate commands: one for stats and one for AST exporting.

**Comment by alessiostalla** [comment]
I don't have any suggestions...

**Comment by mctaverna** [comment]
@ftomassetti 
In my opinion, it would be useful to print statistics about the number of nodes found in a single or in a set of files. 
Something like SELECT DISTINCT node, count(*) GROUP BY node for all nodes in the AST.
The report should include the nodes not present (count = 0) in the file/file set. 
It would be helpful to filter the result by excluding for example the expression subclasses (i.e.Literals) because are not very interesting.

**Comment by ftomassetti** [comment]
Closed by #88
